### ISSUE TITLE
Missing tests checklist

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware-contrib/invenio-checker#2]
#### Reporters
- [ ] Workflow reporter has not been tested (cc @Dziolas)
- [ ] E-mail reporter has not been tested and it should aggregate content before sending the e-mail (cc @Dziolas)
#### Unit
- [ ] `def load_tasks_succesfuly_loads_from_json(self)`
#### Integration
- [ ] `def test_confirm_hash_on_commit_skips_records(self)`
  
  When `confirm_hash_on_commit` is enabled: (a) records that whose hash has changed in the meantime should not be comitted (b) their CheckerRecord.last_run_version_id should NOT be updated.
- [ ] Test that the scheduler runs on the right moments in time only. Decide what is to happen when a task is already running and the scheduler says that it should run again.
- [ ] Check that when `allowed_paths` and `allowed_recids` in a check return bad values, we exit gracefully (ie set the master to failed state). Here is the specification on what they should accept (will eventually be in the documentation) :
  
  -> `allowed_paths` | `['/foo', '/bar/baz']` means "paths '/foo', '/bar/baz'"
  -> `allowed_paths` | `[]` means "all paths"
  -> `allowed_paths` | `None` means "no paths"
  
  -> `allowed_recids` | `{1,2,3}` means "recids 1,2,3"
  -> `allowed_recids` | `{}` means "all recids"
  -> `allowed_recids` | `None` means "no recids"
